# SPDX-License-Identifier: MIT OR Apache-2.0
# .github/workflows/ci.yml - CI pipeline for miniOS v1.7
# Builds, tests, and analyzes miniOS on ARM64 and RISC-V in QEMU
# @version 1.7

name: miniOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # Pin to Ubuntu 22.04 for stability
    strategy:
      matrix:
        arch: [ arm64, riscv64 ]
    steps:
      - uses: actions/checkout@v4  # Upgrade to v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/ci.yml') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades \
            build-essential \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu \
            gcc-riscv64-linux-gnu g++-riscv64-linux-gnu binutils-riscv64-linux-gnu \
            qemu-system-arm qemu-system-riscv64 clang-tidy bear doxygen
      - name: Generate compilation database
        run: bear -- make clean TARGET=${{ matrix.arch }}
      - name: Run static analysis
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -exec clang-tidy --quiet -p compile_commands.json {} \;
      - name: Build miniOS (${{ matrix.arch }})
        run: make TARGET=${{ matrix.arch }}
      - name: Run tests in QEMU (${{ matrix.arch }})
        run: |
          timeout 30s sh -c 'echo -e "test\n" | ${{ matrix.arch == "arm64" && "qemu-system-aarch64 -M virt -cpu cortex-a53 -smp 4 -m 128M -nographic -kernel miniOS.bin" || "qemu-system-riscv64 -M virt -cpu rv64 -smp 4 -m 128M -nographic -kernel miniOS.bin" }}' > test_output.txt
          grep "Tests completed:.*0 failed" test_output.txt
      - name: Generate documentation
        run: doxygen Doxyfile
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Upgrade to v4
        with:
          name: miniOS-${{ matrix.arch }}
          path: |
            miniOS.bin
            docs/html/